"""update items and recipes

Revision ID: 044afe989c13
Revises: bebd883a1327
Create Date: 2026-05-01 14:37:15.659300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '044afe989c13'
down_revision: Union[str, Sequence[str], None] = 'bebd883a1327'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('is_barterable', sa.BOOLEAN(), nullable=False))
    op.create_index(op.f('ix_items_is_barterable'), 'items', ['is_barterable'], unique=False)
    op.add_column('recipes', sa.Column('offer_index', sa.INTEGER(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'offer_index')
    op.drop_index(op.f('ix_items_is_barterable'), table_name='items')
    op.drop_column('items', 'is_barterable')
    # ### end Alembic commands ###
