"""change max size of items id

Revision ID: 0e6c3a6f3a0f
Revises: b52d1c765d32
Create Date: 2026-05-27 10:55:42.670591

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "0e6c3a6f3a0f"
down_revision: Union[str, Sequence[str], None] = "b52d1c765d32"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "task_progress",
        "ingredient_id",
        existing_type=sa.VARCHAR(length=8),
        type_=sa.VARCHAR(length=5),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "task_progress",
        "ingredient_id",
        existing_type=sa.VARCHAR(length=5),
        type_=sa.VARCHAR(length=8),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
