"""add table to log resource actions

Revision ID: 2283b9573a64
Revises: 2f46311a977e
Create Date: 2026-06-05 18:22:18.812501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2283b9573a64'
down_revision: Union[str, Sequence[str], None] = '2f46311a977e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('task_id', sa.INTEGER(), nullable=False),
    sa.Column('ingredient_id', sa.VARCHAR(length=5), nullable=False),
    sa.Column('action_type', sa.Enum('ADD', 'RESET', name='resourceactiontype'), nullable=False),
    sa.Column('delta_value', sa.INTEGER(), nullable=False),
    sa.Column('old_amount', sa.INTEGER(), nullable=False),
    sa.Column('new_amount', sa.INTEGER(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resource_logs_action_type'), 'resource_logs', ['action_type'], unique=False)
    op.create_index(op.f('ix_resource_logs_created_at'), 'resource_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_resource_logs_ingredient_id'), 'resource_logs', ['ingredient_id'], unique=False)
    op.create_index(op.f('ix_resource_logs_task_id'), 'resource_logs', ['task_id'], unique=False)
    op.create_index(op.f('ix_resource_logs_user_id'), 'resource_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resource_logs_user_id'), table_name='resource_logs')
    op.drop_index(op.f('ix_resource_logs_task_id'), table_name='resource_logs')
    op.drop_index(op.f('ix_resource_logs_ingredient_id'), table_name='resource_logs')
    op.drop_index(op.f('ix_resource_logs_created_at'), table_name='resource_logs')
    op.drop_index(op.f('ix_resource_logs_action_type'), table_name='resource_logs')
    op.drop_table('resource_logs')
    # ### end Alembic commands ###
