"""add discount to user tasks model

Revision ID: 24d8a010d02a
Revises: b3e2f7fbe49f
Create Date: 2026-05-06 12:53:18.820116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24d8a010d02a'
down_revision: Union[str, Sequence[str], None] = 'b3e2f7fbe49f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_tasks', sa.Column('discount', sa.INTEGER(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_tasks', 'discount')
    # ### end Alembic commands ###
