"""add relationship between user_tasks and items

Revision ID: 2ebd0b6fe1f1
Revises: 2cc3b498adac
Create Date: 2026-05-02 16:23:05.248709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ebd0b6fe1f1'
down_revision: Union[str, Sequence[str], None] = '2cc3b498adac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
