"""rename 'finished at' field in UserTask

Revision ID: 2f46311a977e
Revises: 1fc561dfc2c8
Create Date: 2026-06-05 14:54:08.014026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2f46311a977e'
down_revision: Union[str, Sequence[str], None] = '1fc561dfc2c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_tasks', sa.Column('finished_at', postgresql.TIMESTAMP(timezone=True), nullable=True))
    op.drop_column('user_tasks', 'completed_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_tasks', sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('user_tasks', 'finished_at')
    # ### end Alembic commands ###
