"""add task progress model and link it to user tasks

Revision ID: 482ae28682d8
Revises: fd795fb900f5
Create Date: 2026-05-09 15:34:19.571111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '482ae28682d8'
down_revision: Union[str, Sequence[str], None] = 'fd795fb900f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.VARCHAR(length=8), nullable=False),
    sa.Column('collected_amount', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['user_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'ingredient_id', name='uq_task_ingredient')
    )
    op.create_index(op.f('ix_task_progress_task_id'), 'task_progress', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_progress_task_id'), table_name='task_progress')
    op.drop_table('task_progress')
    # ### end Alembic commands ###
