"""add finish task stats

Revision ID: 4af6906cea85
Revises: 0e6c3a6f3a0f
Create Date: 2026-06-01 00:57:22.072813

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4af6906cea85"
down_revision: Union[str, Sequence[str], None] = "0e6c3a6f3a0f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    task_status_enum = sa.Enum(
        "IN_PROGRESS", "COMPLETED", "ABANDONED", name="taskstatus"
    )
    task_status_enum.create(op.get_bind(), checkfirst=True)

    op.add_column(
        "user_tasks",
        sa.Column(
            "status", task_status_enum, nullable=False, server_default="IN_PROGRESS"
        ),
    )
    op.alter_column("user_tasks", "status", server_default=None)

    op.add_column(
        "user_tasks",
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "user_tasks",
        sa.Column("completed_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
    )
    op.drop_constraint("uq_user_item_offer", "user_tasks", type_="unique")
    op.create_index(
        op.f("ix_user_tasks_status"), "user_tasks", ["status"], unique=False
    )
    op.create_unique_constraint(
        "uq_user_item_offer_status",
        "user_tasks",
        ["user_id", "item_id", "offer_idx", "status"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_user_item_offer_status", "user_tasks", type_="unique")
    op.drop_index(op.f("ix_user_tasks_status"), table_name="user_tasks")
    op.create_unique_constraint(
        "uq_user_item_offer", "user_tasks", ["user_id", "item_id", "offer_idx"]
    )
    op.drop_column("user_tasks", "completed_at")
    op.drop_column("user_tasks", "created_at")
    op.drop_column("user_tasks", "status")

    task_status_enum = sa.Enum(
        "IN_PROGRESS", "COMPLETED", "ABANDONED", name="taskstatus"
    )
    task_status_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
