"""rename stalcraft db to stalzone

Revision ID: af1fd32f340b
Revises: 2283b9573a64
Create Date: 2026-06-21 09:32:51.955995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'af1fd32f340b'
down_revision: Union[str, Sequence[str], None] = '2283b9573a64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stalzone_version',
    sa.Column('id', sa.VARCHAR(length=6), nullable=False),
    sa.Column('version_sha', sa.VARCHAR(length=40), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('stalcraft_version')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stalcraft_version',
    sa.Column('id', sa.VARCHAR(length=6), autoincrement=False, nullable=False),
    sa.Column('version_sha', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('stalcraft_version_pkey'))
    )
    op.drop_table('stalzone_version')
    # ### end Alembic commands ###
