"""fix relationships, add uniqueconstraint, optimize field types

Revision ID: b3e2f7fbe49f
Revises: 2cc3b498adac
Create Date: 2026-05-03 23:52:03.153081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3e2f7fbe49f'
down_revision: Union[str, Sequence[str], None] = '2cc3b498adac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_recipes_ingredient_id'), 'recipes', ['ingredient_id'], unique=False)
    op.create_index(op.f('ix_recipes_item_id'), 'recipes', ['item_id'], unique=False)
    op.create_unique_constraint('uq_recipe_ingredient', 'recipes', ['item_id', 'ingredient_id', 'offer_index'])
    op.create_index(op.f('ix_user_tasks_item_id'), 'user_tasks', ['item_id'], unique=False)
    op.create_index(op.f('ix_user_tasks_user_id'), 'user_tasks', ['user_id'], unique=False)
    op.create_unique_constraint('uq_user_item_offer', 'user_tasks', ['user_id', 'item_id', 'offer_idx'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_item_offer', 'user_tasks', type_='unique')
    op.drop_index(op.f('ix_user_tasks_user_id'), table_name='user_tasks')
    op.drop_index(op.f('ix_user_tasks_item_id'), table_name='user_tasks')
    op.drop_constraint('uq_recipe_ingredient', 'recipes', type_='unique')
    op.drop_index(op.f('ix_recipes_item_id'), table_name='recipes')
    op.drop_index(op.f('ix_recipes_ingredient_id'), table_name='recipes')
    # ### end Alembic commands ###
