"""add_ing_index_to_recipes

Revision ID: b52d1c765d32
Revises: 482ae28682d8
Create Date: 2026-05-25 00:16:00.041829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b52d1c765d32'
down_revision: Union[str, Sequence[str], None] = '482ae28682d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('ingredient_index', sa.INTEGER(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'ingredient_index')
    # ### end Alembic commands ###
