"""fix uq status in user_tasks

Revision ID: e8b35839c0b3
Revises: 4af6906cea85
Create Date: 2026-06-01 01:20:50.217483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8b35839c0b3'
down_revision: Union[str, Sequence[str], None] = '4af6906cea85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_user_item_offer_status'), 'user_tasks', type_='unique')
    op.create_index('uq_user_item_offer_active', 'user_tasks', ['user_id', 'item_id', 'offer_idx'], unique=True, postgresql_where=sa.text("status = 'IN_PROGRESS'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_user_item_offer_active', table_name='user_tasks', postgresql_where=sa.text("status = 'IN_PROGRESS'"))
    op.create_unique_constraint(op.f('uq_user_item_offer_status'), 'user_tasks', ['user_id', 'item_id', 'offer_idx', 'status'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
