"""add stalcraft version model

Revision ID: fd795fb900f5
Revises: 24d8a010d02a
Create Date: 2026-05-07 20:18:26.665039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fd795fb900f5'
down_revision: Union[str, Sequence[str], None] = '24d8a010d02a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stalcraft_version',
    sa.Column('id', sa.VARCHAR(length=6), nullable=False),
    sa.Column('version_sha', sa.VARCHAR(length=40), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stalcraft_version')
    # ### end Alembic commands ###
